name: Release Test Package

on: workflow_dispatch

jobs:
  BUILD:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python using cache (faster)
        uses: actions/setup-python@v2

      - run: pip3 install --user --upgrade setuptools wheel twine
      - run: python3 setup.py sdist
      - run: python3 -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYP_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYP_TEST_PASSWORD }}


